name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test on minimum supported Python version and potentially latest stable
        python-version: ["3.8", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      # uses: snok/install-poetry@v1 # Switched to pipx method
      run: pipx install poetry

    - name: Install dependencies
      # Add -vvv for more verbose output if install fails
      run: poetry install -vvv --no-interaction --no-ansi

    - name: Run tests
      run: poetry run pytest 