name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test on minimum supported Python version and potentially latest stable
        python-version: ["3.8", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      # run: pipx install poetry # Alternative if snok action has issues

    - name: Install dependencies
      run: poetry install --no-interaction --no-ansi

    - name: Run tests
      run: poetry run pytest 